/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ren
 */
public class account_view extends javax.swing.JFrame {

    /**
     * Creates new form account_view
     */
    public account_view() {
        initComponents();
        load_account();
    }
    
    public void load_account(){
        
        try {
            String homedirec = System.getProperty("user.home");
            String account_name_direc = homedirec + "/carbide/accounts/accounts.csv";
            
            BufferedReader br = null;

            String[] columnNames = new String[0];
            Object[][] data = new Object[0][0];
            String line = "";
            String splitSign = ",";

            int i = 0;
            br = new BufferedReader(new FileReader(account_name_direc));

            while (br.readLine() != null) {
                i++;
            }
            br.close();
            data = new Object[i - 1][];
            i = 0;
            br = new BufferedReader(new FileReader(account_name_direc));
            line = br.readLine();
            columnNames = line.split(splitSign);

            line = br.readLine();
            while (line != null) {
                data[i] = new Object[line.split(splitSign).length];
                
                for (int j = 0; j < data[i].length; j++) {
                    data[i][j] = line.split(splitSign)[j];
                }
                
                i++;
                line = br.readLine();
            }
            
            
            
//            for (String line : Files.readAllLines(Paths.get(account_name_direc + "/accounts.txt"))) {
//                account_names.add(line);
//            }
//                        
//            String[] columnNames = new String[1];
//            columnNames[1] = "Account Name";
//                        
//            Object[][] accounts = new Object[account_names.size()][];
//            int i = 0;
//            for (String c : account_names)
//            {
//                accounts[i] = new Object[1];
//                accounts[i][0] = c;
//                i++;
//            }
            
            jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(model);
            jTable1.setRowSorter(sorter);            
        } catch (IOException ex) {
            Logger.getLogger(account_manager_frame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
