/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ren
 */
public class report_view extends javax.swing.JFrame {

    /**
     * Creates new form report_view
     */
    public report_view() throws IOException {
        initComponents();
        load_account_names();
        load_combined_aggregated_table();
        
    }
    
    public void load_combined_aggregated_table() throws IOException{
        String homedirec = System.getProperty("user.home");
        String combined_aggregated_reports = homedirec + "/carbide/Combined_Data_Entry/all_aggregated_accounts";
           
        BufferedReader br = null;
        
        String[] columnNames = new String[0];
        Object[][] data = new Object[0][0];
        String line = "";
        String splitSign = ",";
        
        File folder = new File(combined_aggregated_reports);
        File[] listOfFiles = folder.listFiles();
        String file = null;
        String filename = null;
        
        for (int i = 0; i < listOfFiles.length; i++){
            
            if (listOfFiles[i].getName().contains(".csv")) {
                file = listOfFiles[i].getPath();
                filename = listOfFiles[i].getName();
                break;
            }
        }
                  
        int i = 0;
        br = new BufferedReader(new FileReader(file));
                    
        while (br.readLine() != null) {
            i++;
        }
        br.close();
        data = new Object[i - 1][];
        i = 0;
        br = new BufferedReader(new FileReader(file));
        line = br.readLine();
        columnNames = line.split(splitSign);
                                    
        line = br.readLine();
        while (line != null) {
            data[i] = new Object[line.split(splitSign).length];

            for (int j = 0; j < data[i].length; j++) {
                data[i][j] = line.split(splitSign)[j];
            }
            i++;
             line = br.readLine();
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
        
    };
    
    public void load_account_names(){
        
        try {
            String homedirec = System.getProperty("user.home");
            String account_name_direc = homedirec + "/carbide/accounts";
            ArrayList<String> account_names = new ArrayList<String>();
            
            account_names.add("ALL");
            
            for (String line : Files.readAllLines(Paths.get(account_name_direc + "/accounts.txt"))) {
                account_names.add(line);
            }
            
            String[] accountarr = new String[account_names.size()];
            accountarr = account_names.toArray(accountarr);
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(accountarr));
            
        } catch (IOException ex) {
            Logger.getLogger(data_entry.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jComboBox1.setSelectedIndex(0);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String account_to_view = String.valueOf(jComboBox1.getSelectedItem());
        
        if (account_to_view.equals("ALL")) {
            try {
                load_combined_aggregated_table();
            } catch (IOException ex) {
                Logger.getLogger(report_view.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                load_separate_aggregation(account_to_view);
            } catch (IOException ex) {
                Logger.getLogger(report_view.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void load_separate_aggregation(String account_name) throws IOException{
        String homedirec = System.getProperty("user.home");
        String combined_aggregated_reports = homedirec + "/carbide/Combined_Data_Entry/separate_aggregated_accounts";
        
        File files = new File(combined_aggregated_reports); 
        String[] fileList = files.list(); 
        
        boolean existed = false;
        String file_to_open = null;
        
        for(String name:fileList){
            if (name.contains(account_name)){
                file_to_open = combined_aggregated_reports + "/" + name;
                existed = true;
            }
        }
        
        if (existed) {
            BufferedReader br = null;
        
            String[] columnNames = new String[0];
            Object[][] data = new Object[0][0];
            String line = "";
            String splitSign = ",";

            int i = 0;
            br = new BufferedReader(new FileReader(file_to_open));

            while (br.readLine() != null) {
                i++;
            }
            br.close();
            data = new Object[i - 1][];
            i = 0;
            br = new BufferedReader(new FileReader(file_to_open));
            line = br.readLine();
            columnNames = line.split(splitSign);

            line = br.readLine();
            while (line != null) {
                data[i] = new Object[line.split(splitSign).length];

                for (int j = 0; j < data[i].length; j++) {
                    data[i][j] = line.split(splitSign)[j];
                }
                i++;
                 line = br.readLine();
            }

            jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
        } else {
            JFrame error_frame = new JFrame();
            JOptionPane.showMessageDialog(error_frame, "Account entries don't exist.", "Error in Account!",JOptionPane.ERROR_MESSAGE);
        }

        
    };
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
